import Head from "next/head";
import Navbar from "./components/Navbar/index";
import Banner from "./components/Banner/index";
import Aboutus from "./components/Aboutus/index";
import Dedicated from "./components/Dedicated/index";
import Ourteam from "./components/Ourteam/index";
import Featured from "./components/Featured/index";
import FAQ from "./components/FAQ/index";
import Testimonials from "./components/Testimonials/index";
import Footer from "./components/Footer/index";

const Home = () => {
  return (
    <>
      <Head>
        <title>Mani Art Sudio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Banner />
        <Aboutus />
        <Dedicated />
        <Ourteam />
        <Featured />
        <FAQ />
        <Testimonials />
        <Footer />
      </main>
    </>
  );
};

export default Home;
